name: Push DevToolz Image
env:
  IMAGE: 'sethsandaru/docking-dev'
  REGISTRY: ghcr.io

on:
  release:
    types: [published]

jobs:
  push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -   uses: actions/checkout@v3
          if: success()

      -   name: Log in to the Container registry
          uses: docker/login-action@v2
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      -   name: Extract metadata (tags, labels) for Normal Image
          id: meta
          uses: docker/metadata-action@v2
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE }}

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            coverage: pcov

      -   name: Setup Node 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'

      -   name: Setup & Build
          if: success()
          run: |
            composer install --no-interaction
            echo "$DEV_IMAGE_ENV" > .env
            php artisan key:generate

            npm ci && npm run build

      -   name: Build and push Docker
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            file: .docker/octane.Dockerfile
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
